### PR TITLE
Pull request to merge changes approved at AIRR 2020 meeting

### PR DESCRIPTION
**Pull request by bcorrie**

### CODE REVIEW

**Comment by bcorrie** [comment]
@bussec @lgcowell (and others), for R13 and Epitopes, I know we want to encourage deposit in known DBs, but is IEDB the only one? Should this be a more general statement and use IEDB as an example? I am far from expert of course, but just wanted to confirm the wording, as it is very explicit where we are not so explicit any where else in this document...

**Comment by lgcowell** [comment]
Well, I think we are so explicit with ImmPort too.

My only thought about IEDB vs the others is I think IEDB has a careful curation process that is perhaps less rigorous with other resources, so I would personally hesitate to recommend the others. Christian correct me if I have the wrong impression.

**Comment by bussec** [comment]
I don't mind explicitly recommending IEDB in R13 as they are IMO providing excellent and systematically curated data and have put a lot of thought into their data models. However, I know that [VDJdb](https://vdjdb.cdr3.net) also has TCR reactivity data, but I only had a look at it at superficial level. So we should probably flag this for review over the next year.

**Comment by bussec** [comment]
Regarding R14: Maybe there is something about ImmPort that I don't understand, but to me it is appears to be a just a repository in which your are obliged to publish your data if you receive funding from a certain funding body (in this case NIH). So R14 basically says that you should comply with your funding agreement. Therefore I was wondering whether we could use more generic language here...

**Comment by bcorrie** [comment]
I think more general language for R14 makes sense - I was always a bit confused about this... My understanding of ImmPort's "ImmPort"ance is that it provides a mechanism to store data that has sharing restrictions on the data. Should the focus of this recommendation be more around how to share data when such restrictions exist? Or is this more about advising researchers to link to AIRR-seq data in the ADC when it is relevant to their studies that are stored on ImmPort???

**Comment by lgcowell** [comment]
I think that makes sense. Recommend IEDB now and then review the others in the coming year to see if we want to recommend them as well.

-------------------------------------------------------------------
Lindsay G. Cowell, PhD
Division of Biomedical Informatics
Department of Population and Data Sciences
Department of Immunology
University of Texas Southwestern Medical Center at Dallas
5323 Harry Hines Blvd.
Dallas, TX  75390-9066

F4.218, MC9066
phone: 214-648-2289
fax: 214-648-2064
Lindsay.Cowell@utsouthwestern.edu<mailto:Lindsay.Cowell@utsouthwestern.edu>

**Comment by lgcowell** [comment]
Yes, that’s true. We could potentially even drop this one. I think originally we were thinking about it in the following way. ImmPort doesn’t take sequencing data, so we were thinking if someone does repertoire sequencing as part of a study that otherwise has to be curated into ImmPort, then that person should put their AIRR-seq data in the AIRR DC and ensure that ImmPort links to that AIRR data. So it’s really not about encouraging people to curate their non-AIRR-seq into ImmPort so much as encouraging people to make sure that any ImmPort studies with an AIRR-seq component put that data in the AIRR DC (no different than our base recommendation) AND make sure that ImmPort links to the AIRR DC. So it is only the last bit that is different.



-------------------------------------------------------------------
Lindsay G. Cowell, PhD
Division of Biomedical Informatics
Department of Population and Data Sciences
Department of Immunology
University of Texas Southwestern Medical Center at Dallas
5323 Harry Hines Blvd.
Dallas, TX  75390-9066

F4.218, MC9066
phone: 214-648-2289
fax: 214-648-2064
Lindsay.Cowell@utsouthwestern.edu<mailto:Lindsay.Cowell@utsouthwestern.edu>

**Comment by lgcowell** [comment]
The latter …

-------------------------------------------------------------------
Lindsay G. Cowell, PhD
Division of Biomedical Informatics
Department of Population and Data Sciences
Department of Immunology
University of Texas Southwestern Medical Center at Dallas
5323 Harry Hines Blvd.
Dallas, TX  75390-9066

F4.218, MC9066
phone: 214-648-2289
fax: 214-648-2064
Lindsay.Cowell@utsouthwestern.edu<mailto:Lindsay.Cowell@utsouthwestern.edu>

**Comment by bcorrie** [comment]
Hmmm @bussec it looks like this was never merged into master. We should merge this into master and then base our changes for 2022 off of that I believe... Would you agree?

**Comment by bcorrie** [comment]
Or I suppose we could branch 2022 off of 2020 and then merge them both into master after ratification at the AIRR meeting.

**Pull request merged**
